const Map<String, String> enDict = {
  // Authentication
  'welcome': 'Welcome',
  'hello': 'Hello',
  'bookYourRide': 'Book your ride',
  'phone': 'Phone Number',
  'password': 'Password',
  'login': 'Login',
  'signUp': 'Sign Up',
  'logout': 'Logout',
  'experience': 'Experience',
  'rating': 'Rating',
  'vehicleNumber': 'Vehicle Number',
  'vehicleType': 'Vehicle Type',
  'readyToRide': 'Ready to ride?',
  'riderProfile': 'Select your profile and begin your city ride.',
  'imRider': "I'm a Rider",
  'imDriver': "I'm a Driver",

  // Feature Badges
  'fastBooking': 'Fast booking',
  'secureTrips': 'Secure trips',
  'liveTracking': 'Live tracking',

  // Authentication extra
  'riderLogin': 'Rider Login',
  'riderSignUp': 'Rider Sign Up',
  'userLoginSub': 'Enter your registered mobile number to login.',
  'userSignUpSub': 'Create your account to start booking rides.',
  'fullName': 'Full name',
  'mobileNumberPlaceholder': 'Mobile number (10 digits)',

  // Driver Auth
  'driverLogin': 'Driver Login',
  'driverSignUp': 'Driver Sign Up',
  'driverLoginSub': 'Login with mobile number and vehicle number.',
  'driverSignUpSub': 'Create your driver account to start accepting rides.',
  'personalDetails': 'Personal Details',
  'licenseIdentity': 'License & Identity',
  'vehicleDetails': 'Vehicle Details',
  'vehicleNumberPlaceholder': 'Vehicle Number (e.g. DL1AB1234)',
  'importProfilePhoto': 'Import Profile photo',
  'emailAddress': 'Email address',
  'drivingLicenseNumber': 'Driving License Number',
  'importLicensePhoto': 'Import Driving License Photo',
  'aadharNumber': 'Aadhaar Number',
  'importAadharFront': 'Import Aadhaar Front Photo',
  'importAadharBack': 'Import Aadhaar Back Photo',
  'importRc': 'Import RC Photo',
  'importInsurance': 'Import Insurance Photo',
  'importPuc': 'Import PUC Photo',
  'switchToSignUp': 'Switch to Sign Up',

  // Driver Auth validation errors
  'errEnterMobile': 'Please enter your mobile number.',
  'errEnterVehicle': 'Please enter your vehicle number.',
  'errLooksLikeVehicle':
      'That looks like a vehicle number. Enter your 10-digit mobile in the field above, and the plate (e.g. DL1AB1234) in Vehicle Number.',
  'errValidMobile': 'Enter a valid 10-digit mobile number (e.g. 9876543210).',
  'errValidVehicle':
      'Enter a valid vehicle number (e.g. DL01AB1234 or DL1AB1234).',
  'errProfilePhoto': 'Please provide a profile photo.',
  'errEnterName': 'Please enter your full name.',
  'errEnterEmail': 'Please enter your email.',
  'errValidEmail': 'Please enter a valid email address.',
  'errLicenseNo': 'Please enter your driving license number.',
  'errLicensePhoto': 'Please provide your driving license photo.',
  'errAadharNo': 'Please enter your Aadhaar number.',
  'errAadharFront': 'Please provide Aadhaar front photo.',
  'errAadharBack': 'Please provide Aadhaar back photo.',
  'errRcPhoto': 'Please provide RC photo.',
  'errInsurancePhoto': 'Please provide insurance photo.',
  'errPucPhoto': 'Please provide PUC photo.',

  'errNoAccountFound':
      'No account found for this number. Please sign up first.',
  'errNumberRegistered':
      'This number may already be registered. Try the Login tab.',
  'errReachServer': 'Could not reach server. Please try again.',
  'errDriverPending':
      'Please wait for document verification. You can login once your documents are verified.',
  'errDriverSubmitted':
      'Documents submitted for verification. You will be able to login once approved.',
  'errDriverRejected':
      'Your verification has been rejected. Please update your documents.',
  'errDriverInvalidCredentials':
      'Invalid mobile or vehicle number. If you are not registered yet, switch to Sign Up.',
  'errDriverDuplicateMobile':
      'This mobile number is already registered. Try the Login tab. If you never signed up before, contact admin to clear your account.',
  'errDriverRegServerError': 'Server error during registration.',
  'errDriverUploadFailed':
      'Could not upload documents. Try again or skip uploads for now.',
  'registrationSuccess': 'Registration successful! Please log in to continue.',

  // Home Screen
  'rideCategories': 'Ride categories',
  'enterPickup': 'Enter pickup location',
  'enterDest': 'Enter destination',
  'chooseRide': 'Choose ride',
  'recentPlaces': 'Recent places',
  'liveMap': 'Live map',
  'pickUpFrom': 'Pick up from',
  'whereTo': 'Where to?',
  'home': 'Home',
  'logoutConfirm': 'Are you sure you want to logout?',
  'cancel': 'Cancel',
  'trips': 'Trips',
  'errDriverLogout':
      'Unable to logout safely. Please check your connection and try again.',

  // Trip Progress / Active Ride
  'tripProgress': 'Trip Progress',
  'rideAssigned': 'Ride Assigned',
  'driverAccepted': 'Driver Accepted',
  'tripStarted': 'Trip Started',
  'completed': 'Completed',
  'rideCompleted': 'Ride Completed',
  'cancelled': 'Cancelled',
  'ongoing': 'Ongoing',
  'lookingForDriver': 'Looking for Driver',
  'driverOnWay': 'Driver is on the way',
  'rideInProgress': 'Ride in progress',
  'waitingForDriver': 'Waiting for driver',
  'rateDriver': 'Rate your driver',
  'experienceQuestion': 'How was your ride experience?',
  'submitRating': 'Submit Rating',
  'bookAnother': 'Book Another Ride',
  'chooseYourRide': 'Choose Your Ride',
  'availableRides': 'Available Rides',
  'driverFound': 'Driver found',
  'searchingDriver': 'Searching for a driver',
  'confirmRide': 'Confirm Ride',
  'activeRide': 'Active Ride',
  'exitConfirm': 'You have an active ride. Are you sure you want to exit?',
  'stay': 'Stay',
  'exit': 'Exit',
  'ratingSuccess': '🎉 Rating submitted successfully!',
  'totalFare': 'Total Fare',

  // Trip History
  'myRides': 'My Rides',
  'rideHistory': 'Ride history',
  'historySub': 'Your recent rides and driver ratings at a glance.',
  'driver': 'Driver',
  'date': 'Date',
  'fare': 'Fare',
  'distance': 'Distance',
  'duration': 'Duration',
  'rideDetails': 'Ride Details',
  'cancelRideQuestion': 'Cancel Ride?',
  'cancelRideConfirm': 'Are you sure you want to cancel this ride request?',
  'no': 'No',
  'yesCancel': 'Yes, Cancel',
  'cancellingRide': 'Cancelling ride...',
  'cancelSuccess': 'Ride cancelled successfully.',
  'driverNotified': 'Driver has been notified.',
  'driverArriveSoon': 'Driver will arrive soon.',
  'arriving': 'Arriving',
  'rateExperience': 'Please rate your experience.',
  'rideConfirmed': 'Ride confirmed',
  'waitingForDriverAccept': 'Waiting for driver to accept…',
  'retry': 'Retry',
  'submitting': 'Submitting…',
  'submitReview': 'Submit review',
  'shareExperience': 'Share your ride experience',
  'rateDriverFeedback': 'Rate your driver and add feedback.',
  'rideComplete': 'Ride complete',
  'pleaseBookAgain': 'Please book again',
  'cancelRide': 'Cancel Ride',
  'errAcceptFailed': 'Failed to accept ride',
  'acceptSuccess': '✅ Ride accepted successfully!',
  'declineRequestQuestion': 'Decline Request?',
  'declineConfirm': 'Are you sure you want to decline this ride request?',
  'decline': 'Decline',
  'declineFailed': 'Ride declined (could not reach server)',
  'accept': 'Accept',
  'newRideRequest': 'New Ride Request',
  'rideDeclined': 'Ride Declined',
  'declineNotify': 'You have declined this ride. The user has been notified.',
  'ok': 'OK',

  // Profile Screen
  'profile': 'Profile',
  'name': 'Name',
  'language': 'Language',
  'english': 'English',
  'hindi': 'Hindi',
  'save': 'Save',
  'edit': 'Edit',
  'rideSection': 'Ride Section',
  'email': 'Email ID',
  'status': 'Status',
  'driverId': 'Driver ID',
  'onlineStatus': 'Online Status',

  // Errors / Info
  'enterPickupErr': 'Please enter a pickup location first.',
  'enterDestErr': 'Please enter a destination first.',
  'noRidesYet': 'No completed rides yet. Book a ride to see your history here.',

  // Driver Active Ride Screen & History/Details
  'passengerInformation': 'Passenger Information',
  'tripDetails': 'Trip Details',
  'pickupLocation': 'Pickup Location',
  'estimatedFare': 'Estimated Fare',
  'startRide': 'Start Ride',
  'completeRide': 'Complete Ride',
  'completing': 'Completing…',
  'startRidePrompt': 'Start the ride after passenger pickup',
  'liveRoute': 'Live Route',
  'loadingRoute': 'Loading route…',
  'loadingRideDetails': 'Loading ride details...',
  'confirmComplete': 'Confirm Complete',
  'fareSetByPassenger': 'Fare set by passenger',
  'confirmRideCompletion':
      'Confirm ride completion. The fare was set by the passenger.',
  'rideCancelledByRider': 'Ride has been cancelled by the user.',
  'pleaseStartRideFirst': 'Please start the ride first before completing it.',
  'rideCancelled': 'Ride cancelled',

  // Trip History Screen
  'searchHistoryPlaceholder': 'Search passenger, pickup, drop...',
  'tripHistory': 'Trip History',
  'route': 'Route',
  'timeline': 'Timeline',
  'completedAt': 'Completed At',
  'fareDetails': 'Fare Details',
  'notes': 'Notes',
  'rideId': 'Ride ID',
  'startTime': 'Start Time',
  'endTime': 'End Time',

  'noMatchingTrips': 'No matching trips found',
  'noTripsYet': 'No trips yet',
  'adjustFilters': 'Try adjusting your filters or search query.',
  'completeRideToSeeHistory': 'Complete a ride to see it in your history.',
  'resetAllFilters': 'Reset All Filters',
  'filterAndSort': 'Filter & Sort',
  'resetAll': 'Reset All',
  'sortBy': 'Sort By',

  // Driver Profile Screen
  'basicInformation': 'Basic Information',
  'profilePhoto': 'Profile photo',
  'tapToViewOrChange': 'Tap to view or change',
  'tapToUpload': 'Tap to upload',
  'goOnlineOfflineToggle': 'Go online / offline toggle',
  'vehicleInformation': 'Vehicle Information',
  'vehicleModel': 'Vehicle model',
  'vehicleColor': 'Vehicle color',
  'documentStatus': 'Document status',
  'drivingLicense': 'Driving license',
  'rcDoc': 'Registration Certificate (RC)',
  'insuranceDoc': 'Vehicle Insurance',
  'pucDoc': 'Pollution Certificate (PUC)',
  'verificationStatus': 'Verification status',
  'verified': 'Verified',
  'pending': 'Pending',
  'uploaded': 'Uploaded',
  'notUploaded': 'Not uploaded',
  'accountControl': 'Account Control',
  'deleteAccount': 'Delete Account',
  'requestDeletion': 'Request permanent deletion',
  'deleteAccountConfirmTitle': 'Delete Account?',
  'deleteAccountConfirmBody':
      'Are you sure you want to submit an account deletion request? Your account will be reviewed and deleted by our team.',
  'submitRequest': 'Submit Request',
  'viewPhoto': 'View Photo',
  'changePhoto': 'Change Photo',
  'profilePhotoSuccess': 'Profile photo updated successfully.',
  'uploadFailed': 'Upload failed: ',
  'galleryError': 'Could not open gallery. Please try again.',
  'deletionRequestSubmitted':
      'Deletion request submitted. Your account will be deleted shortly.',
  'failedSubmitRequest': 'Failed to submit request: ',
  'loadProfileError': 'Could not load profile. Showing saved data.',
  'supportSafety': 'Support & Safety',
  'complaint': 'Complaint',
  'helpCenter': 'Help center',
  'other': 'Other',
  'aboutUs': 'About us',
  'privacyPolicy': 'Privacy policy',
  'termsConditions': 'Terms & conditions',
  'completedCancelled': 'Completed · Cancelled',
  'pleaseSignInComplaint': 'Please sign in to submit a complaint.',
  'change': 'Change',
  'couldNotLoadPhoto': 'Could not load photo',
  'getStarted': 'Get started',
  'skip': 'Skip',
  'next': 'Next',
  'onboardingTitle1': 'Welcome to Chal Chal Gadi',
  'onboardingSub1': 'Ride with confidence, comfort, and speed in every trip.',
  'onboardingTitle2': 'Track rides in real time',
  'onboardingSub2':
      'See driver arrival, route progress, and ETA before every ride.',
  'onboardingTitle3': 'Safe rides always',
  'onboardingSub3':
      'Verified drivers, secure routes, and reliable trip support.',
  'onboardingTitle4': 'Fast booking',
  'onboardingSub4':
      'Book your next ride in seconds with simple, intuitive flow.',

  // Available Drivers & Fare
  'availableDrivers': 'Available Drivers',
  'refresh': 'Refresh',
  'searchDriverHint': 'Search by name, vehicle…',
  'fetchingDrivers': 'Fetching nearby drivers…',
  'callThenAssign': 'Call driver first, then assign the ride',
  'serverCacheDrivers': 'Could not reach server. Showing cached drivers.',
  'driverFoundSingular': 'driver found',
  'driversFound': 'drivers found',
  'noDriversAvailable': 'No drivers available right now.',
  'searchingForDrivers': 'Searching for drivers...',
  'noDriversMatchSearch': 'No drivers match your search.',
  'tryAgain': 'Try again',
  'assigningDriver': 'Assigning driver…',
  'unableOpenDialer': 'Unable to open phone dialer.',
  'invalidDriver': 'Invalid driver. Please try again.',
  'rideAssignedSuccess': 'Ride assigned to',
  'fareLabel': 'Fare',
  'driverNotifyShortly': 'Driver will receive notification shortly.',
  'couldNotAssignRide': 'Could not assign ride on server.',
  'unknownDriver': 'Unknown Driver',
  'noVehicleInfo': 'No vehicle info',
  'online': 'Online',
  'offline': 'Offline',
  'kmAway': 'km away',
  'call': 'Call',
  'assign': 'Assign',
  'assignRideTo': 'Assign this ride to',
  'enterFareHint': 'Enter fare amount (₹)',
  'fareAmountRequired': 'Fare Amount *',
  'fareDiscussNote': 'Enter the fare amount you discussed with the driver',
  'driverNotifyFare':
      'The driver will be notified with the fare and can accept or decline.',
  'confirmAssignment': 'Confirm Assignment',
  'enterFareFirst': 'Enter Fare First',
  'fareRequiredToComplete': 'Passenger fare not found. Cannot complete ride.',

  // Select Ride
  'routePreview': 'Route Preview',
  'loading': 'Loading…',
  'fastRoute': 'Fast route',
  'discussPriceWithDriver': 'Discuss price\nwith driver',
  'mins': 'mins',
  'minsAway': 'mins away',
  'discuss': 'Discuss',
  'dropSoon': 'Drop soon',
  'premiumRide': 'Premium ride',
  'oneMin': '1 min',
  'pendingRide': 'Pending Ride',
  'activeBookingInProgress': 'Active Booking in Progress',
  'resumeRide': 'Resume Ride',
  'cancelRideBtn': 'Cancel Ride',
  'noPendingRides': 'No pending rides',
};
