const Map<String, String> hiDict = {
  // Authentication
  'welcome': 'स्वागत है',
  'hello': 'नमस्ते',
  'bookYourRide': 'अपनी सवारी बुक करें',
  'phone': 'फ़ोन नंबर',
  'password': 'पासवर्ड',
  'login': 'लॉगिन',
  'signUp': 'साइन अप',
  'logout': 'लॉगआउट',
  'experience': 'अनुभव',
  'rating': 'रेटिंग',
  'vehicleNumber': 'गाड़ी का नंबर',
  'vehicleType': 'गाड़ी का प्रकार',
  'readyToRide': 'सवारी के लिए तैयार हैं?',
  'riderProfile': 'अपनी प्रोफ़ाइल चुनें और अपनी शहर की सवारी शुरू करें।',
  'imRider': 'मैं एक यात्री हूँ',
  'imDriver': 'मैं एक चालक हूँ',

  // Feature Badges
  'fastBooking': 'त्वरित बुकिंग',
  'secureTrips': 'सुरक्षित यात्रा',
  'liveTracking': 'लाइव ट्रैकिंग',

  // Authentication extra
  'riderLogin': 'यात्री लॉगिन',
  'riderSignUp': 'यात्री साइन अप',
  'userLoginSub': 'लॉगिन करने के लिए अपना पंजीकृत मोबाइल नंबर दर्ज करें।',
  'userSignUpSub': 'सवारी बुक करना शुरू करने के लिए अपना खाता बनाएं।',
  'fullName': 'पूरा नाम',
  'mobileNumberPlaceholder': 'मोबाइल नंबर (10 अंक)',

  // Driver Auth
  'driverLogin': 'चालक लॉगिन',
  'driverSignUp': 'चालक साइन अप',
  'driverLoginSub': 'मोबाइल नंबर और गाड़ी के नंबर के साथ लॉगिन करें।',
  'driverSignUpSub':
      'सवारी स्वीकार करना शुरू करने के लिए अपना चालक खाता बनाएं।',
  'personalDetails': 'व्यक्तिगत विवरण',
  'licenseIdentity': 'लाइसेंस और पहचान',
  'vehicleDetails': 'गाड़ी का विवरण',
  'vehicleNumberPlaceholder': 'गाड़ी का नंबर (उदा. DL1AB1234)',
  'importProfilePhoto': 'प्रोफ़ाइल फ़ोटो अपलोड करें',
  'emailAddress': 'ईमेल पता',
  'drivingLicenseNumber': 'ड्राइविंग लाइसेंस नंबर',
  'importLicensePhoto': 'ड्राइविंग लाइसेंस फ़ोटो अपलोड करें',
  'aadharNumber': 'आधार नंबर',
  'importAadharFront': 'आधार फ्रंट फ़ोटो अपलोड करें',
  'importAadharBack': 'आधार बैक फ़ोटो अपलोड करें',
  'importRc': 'आरसी फ़ोटो अपलोड करें',
  'importInsurance': 'बीमा फ़ोटो अपलोड करें',
  'importPuc': 'पीयूसी फ़ोटो अपलोड करें',
  'switchToSignUp': 'साइन अप पर जाएं',

  // Driver Auth validation errors
  'errEnterMobile': 'कृपया अपना मोबाइल नंबर दर्ज करें।',
  'errEnterVehicle': 'कृपया अपनी गाड़ी का नंबर दर्ज करें।',
  'errLooksLikeVehicle':
      'यह गाड़ी का नंबर लगता है। ऊपर के फ़ील्ड में अपना 10 अंकों का मोबाइल दर्ज करें, और गाड़ी का नंबर प्लेट नीचे दर्ज करें।',
  'errValidMobile':
      'एक वैध 10 अंकों का मोबाइल नंबर दर्ज करें (उदा. 9876543210)।',
  'errValidVehicle':
      'एक वैध गाड़ी का नंबर दर्ज करें (उदा. DL01AB1234 या DL1AB1234)।',
  'errProfilePhoto': 'कृपया प्रोफ़ाइल फ़ोटो प्रदान करें।',
  'errEnterName': 'कृपया अपना पूरा नाम दर्ज करें।',
  'errEnterEmail': 'कृपया अपना ईमेल दर्ज करें।',
  'errValidEmail': 'कृपया एक वैध ईमेल पता दर्ज करें।',
  'errLicenseNo': 'कृपया अपना ड्राइविंग लाइसेंस नंबर दर्ज करें।',
  'errLicensePhoto': 'कृपया अपना ड्राइविंग लाइसेंस फ़ोटो प्रदान करें।',
  'errAadharNo': 'कृपया अपना आधार नंबर दर्ज करें।',
  'errAadharFront': 'कृपया आधार फ्रंट फ़ोटो प्रदान करें।',
  'errAadharBack': 'कृपया आधार बैक फ़ोटो प्रदान करें।',
  'errRcPhoto': 'कृपया आरसी फ़ोटो प्रदान करें।',
  'errInsurancePhoto': 'कृपया बीमा फ़ोटो प्रदान करें।',
  'errPucPhoto': 'कृपया पीयूसी फ़ोटो प्रदान करें।',

  'errNoAccountFound':
      'इस नंबर के लिए कोई खाता नहीं मिला। कृपया पहले साइन अप करें।',
  'errNumberRegistered':
      'यह नंबर पहले से पंजीकृत हो सकता है। लॉगिन टैब आज़माएं।',
  'errReachServer': 'सर्वर से संपर्क नहीं हो सका। कृपया पुनः प्रयास करें।',
  'errDriverPending':
      'कृपया दस्तावेज़ सत्यापन की प्रतीक्षा करें। आपके दस्तावेज़ों के सत्यापित होने के बाद आप लॉगिन कर सकते हैं।',
  'errDriverSubmitted':
      'दस्तावेज़ सत्यापन के लिए सबमिट कर दिए गए हैं। स्वीकृत होने के बाद आप लॉगिन कर सकेंगे।',
  'errDriverRejected':
      'आपका सत्यापन अस्वीकार कर दिया गया है। कृपया अपने दस्तावेज़ अपडेट करें।',
  'errDriverInvalidCredentials':
      'अमान्य मोबाइल या गाड़ी का नंबर। यदि आप अभी तक पंजीकृत नहीं हैं, तो साइन अप पर जाएं।',
  'errDriverDuplicateMobile':
      'यह मोबाइल नंबर पहले से पंजीकृत है। लॉगिन टैब आज़माएं। अगर आपने पहले कभी साइन अप नहीं किया, तो अपना अकाउंट हटवाने के लिए एडमिन से संपर्क करें।',
  'errDriverRegServerError': 'पंजीकरण के दौरान सर्वर त्रुटि।',
  'errDriverUploadFailed':
      'दस्तावेज़ अपलोड नहीं किए जा सके। पुनः प्रयास करें या अभी के लिए अपलोड छोड़ दें।',
  'registrationSuccess': 'पंजीकरण सफल रहा! कृपया जारी रखने के लिए लॉगिन करें।',

  // Home Screen
  'rideCategories': 'सवारी की श्रेणियां',
  'enterPickup': 'पिकअप स्थान दर्ज करें',
  'enterDest': 'गंतव्य स्थान दर्ज करें',
  'chooseRide': 'सवारी चुनें',
  'recentPlaces': 'हाल के स्थान',
  'liveMap': 'लाइव मानचित्र',
  'pickUpFrom': 'यहाँ से पिकअप',
  'whereTo': 'कहाँ जाना है?',
  'home': 'होम',
  'logoutConfirm': 'क्या आप सचमुच लॉगआउट करना चाहते हैं?',
  'cancel': 'रद्द करें',
  'trips': 'यात्राएं',
  'errDriverLogout':
      'लॉगआउट करने में असमर्थ। कृपया अपना कनेक्शन जांचें और पुनः प्रयास करें।',

  // Trip Progress / Active Ride
  'tripProgress': 'यात्रा की प्रगति',
  'rideAssigned': 'सवारी आवंटित की गई',
  'driverAccepted': 'चालक ने स्वीकार किया',
  'tripStarted': 'यात्रा शुरू हुई',
  'completed': 'पूर्ण',
  'rideCompleted': 'यात्रा पूर्ण हुई',
  'cancelled': 'रद्द कर दिया गया',
  'ongoing': 'चल रहा है',
  'lookingForDriver': 'चालक की तलाश है',
  'driverOnWay': 'चालक रास्ते में है',
  'rideInProgress': 'यात्रा चल रही है',
  'waitingForDriver': 'चालक की प्रतीक्षा की जा रही है',
  'rateDriver': 'चालक को रेट करें',
  'experienceQuestion': 'आपकी यात्रा का अनुभव कैसा रहा?',
  'submitRating': 'रेटिंग सबमिट करें',
  'bookAnother': 'एक और सवारी बुक करें',
  'chooseYourRide': 'अपनी सवारी चुनें',
  'availableRides': 'उपलब्ध सवारियां',
  'driverFound': 'ड्राइवर मिल गया',
  'searchingDriver': 'ड्राइवर की तलाश की जा रही है',
  'confirmRide': 'सवारी की पुष्टि करें',
  'activeRide': 'सक्रिय सवारी',
  'exitConfirm':
      'आपके पास एक सक्रिय सवारी है। क्या आप सचमुच बाहर निकलना चाहते हैं?',
  'stay': 'रुकें',
  'exit': 'बाहर निकलें',
  'ratingSuccess': '🎉 रेटिंग सफलतापूर्वक सबमिट हो गई!',
  'totalFare': 'कुल किराया',

  // Trip History
  'myRides': 'मेरी सवारियां',
  'rideHistory': 'सवारियों का इतिहास',
  'historySub': 'आपकी हालिया सवारियां और चालक रेटिंग एक नज़र में।',
  'driver': 'चालक',
  'date': 'दिनांक',
  'fare': 'किराया',
  'distance': 'दूरी',
  'duration': 'अवधि',
  'rideDetails': 'सवारी का विवरण',
  'cancelRideQuestion': 'सवारी रद्द करें?',
  'cancelRideConfirm':
      'क्या आप सचमुच इस सवारी के अनुरोध को रद्द करना चाहते हैं?',
  'no': 'नहीं',
  'yesCancel': 'हाँ, रद्द करें',
  'cancellingRide': 'सवारी रद्द की जा रही है...',
  'cancelSuccess': 'सवारी सफलतापूर्वक रद्द कर दी गई।',
  'driverNotified': 'ड्राइवर को सूचित कर दिया गया है।',
  'driverArriveSoon': 'ड्राइवर जल्द ही आ जाएगा।',
  'arriving': 'पहुंच रहा है',
  'rateExperience': 'कृपया अपने अनुभव को रेट करें।',
  'rideConfirmed': 'सवारी की पुष्टि की गई',
  'waitingForDriverAccept':
      'चालक द्वारा स्वीकार किए जाने की प्रतीक्षा की जा रही है…',
  'retry': 'पुनः प्रयास करें',
  'submitting': 'सबमिट किया जा रहा है…',
  'submitReview': 'समीक्षा सबमिट करें',
  'shareExperience': 'अपनी सवारी का अनुभव साझा करें',
  'rateDriverFeedback': 'अपने ड्राइवर को रेट करें और फीडबैक जोड़ें।',
  'rideComplete': 'सवारी पूरी हुई',
  'pleaseBookAgain': 'कृपया पुनः बुक करें',
  'cancelRide': 'सवारी रद्द करें',
  'errAcceptFailed': 'सवारी स्वीकार करने में विफल',
  'acceptSuccess': '✅ सवारी सफलतापूर्वक स्वीकार की गई!',
  'declineRequestQuestion': 'अनुरोध अस्वीकार करें?',
  'declineConfirm':
      'क्या आप सचमुच इस सवारी के अनुरोध को अस्वीकार करना चाहते हैं?',
  'decline': 'अस्वीकार करें',
  'declineFailed': 'सवारी अस्वीकार कर दी गई (सर्वर से संपर्क नहीं हो सका)',
  'accept': 'स्वीकार करें',
  'newRideRequest': 'नया सवारी अनुरोध',
  'rideDeclined': 'सवारी अस्वीकार की गई',
  'declineNotify':
      'आपने यह सवारी अस्वीकार कर दी है। उपयोगकर्ता को सूचित कर दिया गया है।',
  'ok': 'ठीक है',

  // Profile Screen
  'profile': 'प्रोफ़ाइल',
  'name': 'नाम',
  'language': 'भाषा',
  'english': 'अंग्रेज़ी',
  'hindi': 'हिन्दी',
  'save': 'सहेजें',
  'edit': 'संपादित करें',
  'rideSection': 'सवारी अनुभाग',
  'email': 'ईमेल आईडी',
  'status': 'स्थिति',
  'driverId': 'ड्राइवर आईडी',
  'onlineStatus': 'ऑनलाइन स्थिति',

  // Errors / Info
  'enterPickupErr': 'कृपया पहले पिकअप स्थान दर्ज करें।',
  'enterDestErr': 'कृपया पहले गंतव्य स्थान दर्ज करें।',
  'noRidesYet':
      'अभी तक कोई पूर्ण सवारी नहीं है। अपना इतिहास देखने के लिए एक सवारी बुक करें।',

  // Driver Active Ride Screen & History/Details
  'passengerInformation': 'यात्री की जानकारी',
  'tripDetails': 'यात्रा का विवरण',
  'pickupLocation': 'पिकअप स्थान',
  'estimatedFare': 'अनुमानित किराया',
  'startRide': 'सवारी शुरू करें',
  'completeRide': 'सवारी पूरी करें',
  'completing': 'सवारी पूरी की जा रही है…',
  'startRidePrompt': 'यात्री को पिकअप करने के बाद सवारी शुरू करें',
  'liveRoute': 'लाइव मार्ग',
  'loadingRoute': 'मार्ग लोड किया जा रहा है…',
  'loadingRideDetails': 'सवारी का विवरण लोड किया जा रहा है...',
  'confirmComplete': 'पूर्ण करने की पुष्टि करें',
  'fareSetByPassenger': 'यात्री द्वारा निर्धारित किराया',
  'confirmRideCompletion':
      'सवारी पूर्ण करने की पुष्टि करें। किराया यात्री द्वारा निर्धारित किया गया था।',
  'rideCancelledByRider': 'उपयोगकर्ता द्वारा सवारी रद्द कर दी गई है।',
  'pleaseStartRideFirst': 'कृपया सवारी पूरी करने से पहले इसे शुरू करें।',
  'rideCancelled': 'सवारी रद्द कर दी गई',

  // Trip History Screen
  'searchHistoryPlaceholder': 'यात्री, पिकअप, ड्रॉप खोजें...',
  'tripHistory': 'यात्रा का इतिहास',
  'route': 'मार्ग',
  'timeline': 'समय रेखा',
  'completedAt': 'इस समय पूर्ण हुआ',
  'fareDetails': 'किराए का विवरण',
  'notes': 'टिप्पणियां',
  'rideId': 'सवारी आईडी',
  'startTime': 'शुरुआती समय',
  'endTime': 'समाप्ति समय',

  'noMatchingTrips': 'कोई मेल खाती यात्राएं नहीं मिलीं',
  'noTripsYet': 'अभी तक कोई यात्रा नहीं',
  'adjustFilters':
      'अपने फ़िल्टर या खोज क्वेरी को समायोजित करने का प्रयास करें।',
  'completeRideToSeeHistory': 'इतिहास में देखने के लिए एक सवारी पूरी करें।',
  'resetAllFilters': 'सभी फ़िल्टर रीसेट करें',
  'filterAndSort': 'फ़िल्टर और सॉर्ट करें',
  'resetAll': 'सभी रीसेट करें',
  'sortBy': 'इसके अनुसार क्रमबद्ध करें',

  // Driver Profile Screen
  'basicInformation': 'बुनियादी जानकारी',
  'profilePhoto': 'प्रोफ़ाइल फ़ोटो',
  'tapToViewOrChange': 'देखने या बदलने के लिए टैप करें',
  'tapToUpload': 'अपलोड करने के लिए टैप करें',
  'goOnlineOfflineToggle': 'ऑनलाइन / ऑफलाइन टॉगल',
  'vehicleInformation': 'वाहन की जानकारी',
  'vehicleModel': 'वाहन का मॉडल',
  'vehicleColor': 'वाहन का रंग',
  'documentStatus': 'दस्तावेज़ की स्थिति',
  'drivingLicense': 'ड्राइविंग लाइसेंस',
  'rcDoc': 'पंजीकरण प्रमाण पत्र (RC)',
  'insuranceDoc': 'वाहन बीमा',
  'pucDoc': 'प्रदूषण नियंत्रण प्रमाण पत्र (PUC)',
  'verificationStatus': 'सत्यापन की स्थिति',
  'verified': 'सत्यापित',
  'pending': 'लंबित',
  'uploaded': 'अपलोड किया गया',
  'notUploaded': 'अपलोड नहीं किया गया',
  'accountControl': 'खाता नियंत्रण',
  'deleteAccount': 'खाता हटाएं',
  'requestDeletion': 'स्थायी रूप से हटाने का अनुरोध करें',
  'deleteAccountConfirmTitle': 'खाता हटाएं?',
  'deleteAccountConfirmBody':
      'क्या आप वाकई खाता हटाने का अनुरोध सबमिट करना चाहते हैं? हमारी टीम द्वारा आपके खाते की समीक्षा की जाएगी और इसे हटा दिया जाएगा।',
  'submitRequest': 'अनुरोध सबमिट करें',
  'viewPhoto': 'फ़ोटो देखें',
  'changePhoto': 'फ़ोटो बदलें',
  'profilePhotoSuccess': 'प्रोफ़ाइल फ़ोटो सफलतापूर्वक अपडेट की गई।',
  'uploadFailed': 'अपलोड विफल रहा: ',
  'galleryError': 'गैलरी नहीं खोली जा सकी। कृपया पुनः प्रयास करें।',
  'deletionRequestSubmitted':
      'हटाने का अनुरोध सबमिट हो गया है। आपका खाता जल्द ही हटा दिया जाएगा।',
  'failedSubmitRequest': 'अनुरोध सबमिट करने में विफल: ',
  'loadProfileError':
      'प्रोफ़ाइल लोड नहीं की जा सकी। सहेजा गया डेटा दिखाया जा रहा है।',
  'supportSafety': 'सहायता और सुरक्षा',
  'complaint': 'शिकायत',
  'helpCenter': 'सहायता केंद्र',
  'other': 'अन्य',
  'aboutUs': 'हमारे बारे में',
  'privacyPolicy': 'गोपनीयता नीति',
  'termsConditions': 'नियम और शर्तें',
  'completedCancelled': 'पूर्ण · रद्द',
  'pleaseSignInComplaint': 'कृपया शिकायत सबमिट करने के लिए साइन इन करें।',
  'change': 'बदलें',
  'couldNotLoadPhoto': 'फ़ोटो लोड नहीं की जा सकी',
  'getStarted': 'शुरू करें',
  'skip': 'छोड़ें',
  'next': 'आगे',
  'onboardingTitle1': 'चल चल गाड़ी में आपका स्वागत है',
  'onboardingSub1': 'हर यात्रा में विश्वास, आराम और गति के साथ सवारी करें।',
  'onboardingTitle2': 'वास्तविक समय में सवारी ट्रैक करें',
  'onboardingSub2':
      'हर सवारी से पहले चालक का आगमन, मार्ग की प्रगति और ईटीए देखें।',
  'onboardingTitle3': 'हमेशा सुरक्षित सवारी',
  'onboardingSub3': 'सत्यापित चालक, सुरक्षित मार्ग और विश्वसनीय यात्रा सहायता।',
  'onboardingTitle4': 'त्वरित बुकिंग',
  'onboardingSub4':
      'सरल, सहज प्रवाह के साथ सेकंड में अपनी अगली सवारी बुक करें।',

  // Available Drivers & Fare
  'availableDrivers': 'उपलब्ध ड्राइवर',
  'refresh': 'रीफ़्रेश',
  'searchDriverHint': 'नाम, वाहन से खोजें…',
  'fetchingDrivers': 'आस-पास के ड्राइवर खोजे जा रहे हैं…',
  'callThenAssign': 'पहले ड्राइवर को कॉल करें, फिर सवारी असाइन करें',
  'serverCacheDrivers':
      'सर्वर से संपर्क नहीं हो सका। सहेजे गए ड्राइवर दिखाए जा रहे हैं।',
  'driverFoundSingular': 'ड्राइवर मिला',
  'driversFound': 'ड्राइवर मिले',
  'noDriversAvailable': 'अभी कोई ड्राइवर उपलब्ध नहीं है।',
  'searchingForDrivers': 'ड्राइवरों की खोज की जा रही है...',
  'noDriversMatchSearch': 'आपकी खोज से कोई ड्राइवर मेल नहीं खाता।',
  'tryAgain': 'पुनः प्रयास करें',
  'assigningDriver': 'ड्राइवर असाइन किया जा रहा है…',
  'unableOpenDialer': 'फ़ोन डायलर नहीं खोला जा सका।',
  'invalidDriver': 'अमान्य ड्राइवर। कृपया पुनः प्रयास करें।',
  'rideAssignedSuccess': 'सवारी असाइन की गई',
  'fareLabel': 'किराया',
  'driverNotifyShortly': 'ड्राइवर को जल्द ही सूचना मिलेगी।',
  'couldNotAssignRide': 'सर्वर पर सवारी असाइन नहीं की जा सकी।',
  'unknownDriver': 'अज्ञात ड्राइवर',
  'noVehicleInfo': 'वाहन की जानकारी नहीं',
  'online': 'ऑनलाइन',
  'offline': 'ऑफलाइन',
  'kmAway': 'किमी दूर',
  'call': 'कॉल',
  'assign': 'असाइन',
  'assignRideTo': 'इस सवारी को असाइन करें',
  'enterFareHint': 'किराया राशि दर्ज करें (₹)',
  'fareAmountRequired': 'किराया राशि *',
  'fareDiscussNote': 'वह किराया राशि दर्ज करें जिस पर आपने ड्राइवर से बात की',
  'driverNotifyFare':
      'ड्राइवर को किराये के साथ सूचित किया जाएगा और वह स्वीकार या अस्वीकार कर सकता है।',
  'confirmAssignment': 'असाइनमेंट की पुष्टि करें',
  'enterFareFirst': 'पहले किराया दर्ज करें',
  'fareRequiredToComplete':
      'यात्री का किराया नहीं मिला। सवारी पूरी नहीं की जा सकती।',

  // Select Ride
  'routePreview': 'मार्ग पूर्वावलोकन',
  'loading': 'लोड हो रहा है…',
  'fastRoute': 'तेज़ मार्ग',
  'discussPriceWithDriver': 'ड्राइवर से\nकिराया तय करें',
  'mins': 'मिनट',
  'minsAway': 'मिनट दूर',
  'discuss': 'चर्चा करें',
  'dropSoon': 'जल्द पहुँच',
  'premiumRide': 'प्रीमियम सवारी',
  'oneMin': '1 मिनट',
  'pendingRide': 'लंबित सवारी',
  'activeBookingInProgress': 'सक्रिय बुकिंग प्रगति पर है',
  'resumeRide': 'सवारी फिर से शुरू करें',
  'cancelRideBtn': 'सवारी रद्द करें',
  'noPendingRides': 'कोई लंबित सवारी नहीं',
};
